### PR TITLE
Faster tests with php-vcr

### LINKED ISSUE #23: Faster test suite?
Functional tests are awesome but 45 minute test suites are not. Is there any way to decrease the time it takes to run the tests?

### PR DESCRIPTION
**Pull request by justincy**
This is to close #23 by making the tests run faster. I used php-vcr to record the HTTP requests for playback during the tests. A few notes:

* This isn't ready to be merged just yet. The test files run much faster separately, but when I run the whole suite together it only runs about 10 minutes faster. At least locally. I'm submitting the PR to see if it runs faster in travis. Either way, a 35 minute test suite when run locally is still too slow. I've tried disabled garbage collection (as recommended [here](https://scrutinizer-ci.com/blog/composer-gc-performance-who-is-affected-too)) but that didn't have any noticeable impact. So I'm going to start profiling.
* I'm now seeding faker to generate repeatable data. This is necessary to replay recorded responses.
* In one test, you can't make two of the same calls when expecting different data; e.g., reading a person after deleting a conclusion and expecting the response to be different. We are recording and responses are matched with requests based on the HTTP method, URL, and body. About halfway through I figured out how to add a cache breaker to the responses to create unique URLs for matching.
* Tests with files (creating memories) do not work with PHP VCR so they're not being recorded for now.
* ~~I'm not recording vocabularies tests because the recorded data is large and there's only three tests.~~

### CODE REVIEW

**Comment by jimmyz** [comment]
Builds have stalled. One build timed out. The other has been running for almost 2 hours.

**Comment by justincy** [comment]
Which ones stalled? I only see ones with exited early.

**Comment by jimmyz** [comment]
Never mind. I was looking at build 67 and there was some glitch that showed 67.1 had been running for almost 2 hours. 68 looks healthy. I'm going to merge.

**Comment by justincy** [comment]
No, don't merge. It's not ready.

**Comment by jimmyz** [comment]
Oh, yep. I see your comment up above.

**Comment by justincy** [comment]
I got the time down to 15 minutes by switching the storage format of php-vcr from YAML (the default) to JSON. Once the bottleneck of parsing YAML, and JSON embedded in the YAML, then disabled garbage collection did make a difference.

I think 15 minutes is still not ideal. The majority of that time is spent on tests that upload files. A few options for dealing with that:

1. Figure out if and how we could make POSTing files work with php-vcr.
2. Condense the test into a minimal set (or even just one) that tests all features instead of one test for each use case that leads to us authenticating and creating a memory each time.
3. Just accept that we need to get in the habit of using the `--filter` option when running tests locally.

**Comment by justincy** [comment]
Another thing to note is that the tests are behaving strangely in Travis. You can't see the `.`s that represent successful tests in the output unless you view the raw logs. There you'll see that the full test suite doesn't actually complete but terminates early due to an mpdf error. Perhaps a 4th option to the above list would be to stop testing memories :) They're a pain.

**Comment by justincy** [comment]
@jimmyz It's finally ready with a true and repeatable green and a run time below 5 minutes.

So much for 5-10 minutes. I've been fighting all day with Faker not producing repeatable data even when it's seeded. It only affected dates. I finally tracked it down to the Faker DateTime provider being designed to return random dates [relative to a point in time](https://github.com/fzaninotto/Faker/issues/90) which defaults to `now`. Therefore the relative starting point would slide and produce a different date. It took a while to figure that out.

**Comment by adri** [comment]
Huge merge! Congrats and thank you for helping making php-vcr better.

**Comment by jimmyz** [comment]
@adri Thanks for making php-vcr! I'm a big fan of the ruby vcr gem, and was thrilled to see someone had brought this concept to PHP.

**Comment by justincy** [comment]
@adri Thanks for your cooperation in enhancing php-vcr.

**Pull request merged**
